[package]
name = "snake"
version = "0.1.0"
authors = ["Stephen Newman <steve@newman.digital>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
find_folder = "0.3.0"
rand = "0.7.3"
piston_window = "0.109.0"